version: '3.9'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - pgdata:/data/postgres
      - ${PWD}/postgres-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  pgdata:
